
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package lighthouse;

import java_cup.runtime.*;
import java.util.List;
import java.util.LinkedList;
import lighthouse.Instance;
import lighthouse.Predicate;
import LHExceptions.ParserExceptions.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150930 (SVN rev 66) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\041\000\002\002\004\000\002\022\002\000\002\021" +
    "\002\000\002\021\005\000\002\002\006\000\002\002\005" +
    "\000\002\002\005\000\002\003\005\000\002\003\003\000" +
    "\002\004\005\000\002\004\004\000\002\016\006\000\002" +
    "\011\006\000\002\017\006\000\002\005\005\000\002\005" +
    "\003\000\002\010\006\000\002\010\007\000\002\010\005" +
    "\000\002\010\006\000\002\020\005\000\002\020\003\000" +
    "\002\014\006\000\002\014\005\000\002\013\004\000\002" +
    "\013\003\000\002\012\012\000\002\012\011\000\002\006" +
    "\006\000\002\006\005\000\002\007\006\000\002\023\003" +
    "\000\002\015\015" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\006\014\uffff\024\006\001\002\000\004\014" +
    "\000\001\002\000\004\002\011\001\002\000\004\030\007" +
    "\001\002\000\004\024\010\001\002\000\010\002\ufffe\014" +
    "\ufffe\015\ufffe\001\002\000\004\002\001\001\002\000\004" +
    "\014\013\001\002\000\010\003\124\005\121\026\122\001" +
    "\002\000\004\006\016\001\002\000\004\025\075\001\002" +
    "\000\006\005\017\026\020\001\002\000\004\026\020\001" +
    "\002\000\004\011\025\001\002\000\006\004\uffe8\026\uffe8" +
    "\001\002\000\006\004\024\026\020\001\002\000\006\004" +
    "\uffe9\026\uffe9\001\002\000\004\025\uffea\001\002\000\006" +
    "\012\027\026\026\001\002\000\010\004\uffec\012\uffec\020" +
    "\uffec\001\002\000\004\021\067\001\002\000\006\012\032" +
    "\020\031\001\002\000\004\026\066\001\002\000\004\021" +
    "\033\001\002\000\004\007\035\001\002\000\004\010\061" +
    "\001\002\000\004\005\036\001\002\000\010\004\042\023" +
    "\043\026\040\001\002\000\006\004\ufff2\020\ufff2\001\002" +
    "\000\004\011\054\001\002\000\006\004\052\020\051\001" +
    "\002\000\004\010\uffe4\001\002\000\004\026\044\001\002" +
    "\000\004\011\045\001\002\000\006\012\046\026\026\001" +
    "\002\000\006\004\uffee\020\uffee\001\002\000\006\012\050" +
    "\020\031\001\002\000\006\004\ufff0\020\ufff0\001\002\000" +
    "\006\023\043\026\040\001\002\000\004\010\uffe5\001\002" +
    "\000\006\004\ufff3\020\ufff3\001\002\000\006\012\055\026" +
    "\026\001\002\000\006\004\uffef\020\uffef\001\002\000\006" +
    "\012\057\020\031\001\002\000\006\004\ufff1\020\ufff1\001" +
    "\002\000\004\022\065\001\002\000\004\005\062\001\002" +
    "\000\006\023\043\026\040\001\002\000\006\004\064\020" +
    "\051\001\002\000\004\022\uffe3\001\002\000\006\004\uffe7" +
    "\026\uffe7\001\002\000\010\004\uffed\012\uffed\020\uffed\001" +
    "\002\000\004\007\035\001\002\000\004\010\061\001\002" +
    "\000\004\022\072\001\002\000\006\004\uffe6\026\uffe6\001" +
    "\002\000\006\004\074\026\020\001\002\000\004\025\uffeb" +
    "\001\002\000\006\015\uffe2\024\uffe2\001\002\000\006\015" +
    "\uffff\024\006\001\002\000\004\015\101\001\002\000\004" +
    "\013\105\001\002\000\004\005\102\001\002\000\004\026" +
    "\026\001\002\000\006\004\104\020\031\001\002\000\004" +
    "\013\ufff4\001\002\000\004\005\116\001\002\000\004\016" +
    "\110\001\002\000\006\002\uffff\024\006\001\002\000\004" +
    "\005\111\001\002\000\006\023\043\026\040\001\002\000" +
    "\006\004\113\020\051\001\002\000\006\002\ufff5\024\ufff5" +
    "\001\002\000\004\002\000\001\002\000\004\002\uffe1\001" +
    "\002\000\006\023\043\026\040\001\002\000\006\004\120" +
    "\020\051\001\002\000\004\016\ufff6\001\002\000\004\026" +
    "\122\001\002\000\004\017\132\001\002\000\006\004\130" +
    "\020\127\001\002\000\004\004\126\001\002\000\006\004" +
    "\ufff9\020\ufff9\001\002\000\004\006\ufffb\001\002\000\004" +
    "\026\122\001\002\000\004\006\ufffc\001\002\000\006\004" +
    "\ufffa\020\ufffa\001\002\000\010\004\ufff7\020\ufff7\027\133" +
    "\001\002\000\006\004\ufff8\020\ufff8\001\002\000\006\004" +
    "\135\020\127\001\002\000\004\006\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\006\015\004\021\003\001\001\000\004\022" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\002" +
    "\013\001\001\000\006\003\122\004\124\001\001\000\004" +
    "\014\014\001\001\000\004\023\075\001\001\000\006\012" +
    "\020\013\021\001\001\000\006\012\020\013\072\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\012\022\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\020\027" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\033" +
    "\001\001\000\004\007\057\001\001\000\002\001\001\000" +
    "\006\005\040\010\036\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\020\046\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\052\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\020\055\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\062\010\036\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\067" +
    "\001\001\000\004\007\070\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\012\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\021\076\001\001\000\004\017" +
    "\077\001\001\000\004\016\105\001\001\000\002\001\001" +
    "\000\004\020\102\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\106\001\001\000\004" +
    "\021\113\001\001\000\002\001\001\000\006\005\111\010" +
    "\036\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\022\114\001\001\000\002\001\001\000\006\005\116\010" +
    "\036\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\133\004\124\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\130\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




Instance i = new Instance();

public Instance getInstance(){
return i ;
}

private String filename(){
    
    Lexer l = (Lexer) this.getScanner();
    return l.getFilename();
}
public String getWhere(){

    Lexer l = (Lexer) this.getScanner();
    return (l.getFilename()+" line "+(l.getLine()+1)+" col: "+(l.getColumn()+1));
}

public void printWhere(){

    Lexer l = (Lexer) this.getScanner();
    System.out.println("Line "+(l.getLine()+1)+" col: "+(l.getColumn()+1));
}
 public void report_fatal_error(String message, Object info){
    //printWhere();
    report_error(message,info);
    throw new SyntaxErrorError("Syntax error");
    //super.report_fatal_error("",info);
}


@Override
	protected void report_expected_token_ids() {
	  List<Integer> ids = expected_token_ids();
	  LinkedList<String> list = new LinkedList<String>();
	  for (Integer expected : ids)
		  list.add(symbl_name_from_id(expected));
	  String msg = "instead expected token classes are " + list + "error token is "+ symbl_name_from_id(super.cur_token.sym);
	  System.err.println(msg);
//errMan.Error(ErrorSource.Parser, msg);
	}

private void warningMissing(String str){
System.err.println("WARNING: Missing \""+str+"\" in "+getWhere());
}
private void error(String str){
System.err.println("ERROR:  "+str);
throw new SyntaxErrorError("Syntax error");
}

private void abort(){
System.exit(1);
}

protected int error_sync_size(){
return 1;
}
    

public void report_error(String message, Object info) {
   
        StringBuffer m = new StringBuffer("Error");
        m.append(filename());
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));   
                if (s.right >= 0)                    
                    m.append(", column "+(s.right+1));
            }
        }
   
        m.append(" : "+message);
   
        System.err.println(m);
        //super.report_error("",info);
    }




/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= PDDL EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // runscripts ::= 
            {
              Object RESULT =null;
		i.runScripts();
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("runscripts",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // script ::= 
            {
              Object RESULT =null;
		
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("script",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // script ::= SCRIPTBOUND SCRIPTCODE SCRIPTBOUND 
            {
              Object RESULT =null;
		int codeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int coderight = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String code = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		System.out.println(code);i.addScript(code);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("script",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // predicatesdecl ::= PREDICATES COL predicateDeclarationList SEMI 
            {
              Object RESULT =null;
		
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicatesdecl",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // predicatesdecl ::= PREDICATES predicateDeclarationList SEMI 
            {
              Object RESULT =null;
		warningMissing(":"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicatesdecl",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // predicatesdecl ::= PREDICATES error SEMI 
            {
              Object RESULT =null;
		 error("syntax error in the predicate declaration"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicatesdecl",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // predicateDeclarationList ::= predicateDeclarationList COMMA predicateDeclaration 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicateDeclarationList",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // predicateDeclarationList ::= predicateDeclaration 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicateDeclarationList",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // predicateDeclaration ::= ID SLASH NUMBER 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int numleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		i.registerPredicate(name,num);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicateDeclaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // predicateDeclaration ::= ID SLASH 
            {
              Object RESULT =null;
		 error("Missing number, should be predicate/arity"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicateDeclaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // initialdecl ::= INITIAL COL predicates SEMI 
            {
              Object RESULT =null;
		int pcsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pcsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<PredicateInst> pcs = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  i.setInitial(pcs); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("initialdecl",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // finaldecl ::= FINAL COL predicates SEMI 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<PredicateInst> p = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 i.setFinal(p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("finaldecl",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // constantsdecl ::= CONSTANTS COL mixlist SEMI 
            {
              Object RESULT =null;
		int clleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<String> cl = (List<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  for (String c : cl){ i.registerConstant(c); } 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("constantsdecl",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // predicates ::= predicates COMMA predicate 
            {
              List<PredicateInst> RESULT =null;
		int ppleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int ppright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<PredicateInst> pp = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		PredicateInst p = (PredicateInst)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = pp; pp.add(p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicates",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // predicates ::= predicate 
            {
              List<PredicateInst> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		PredicateInst p = (PredicateInst)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LinkedList<PredicateInst>(); RESULT.add(p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicates",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // predicate ::= ID LPAREN mixlist RPAREN 
            {
              PredicateInst RESULT =null;
		int pnameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pnameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String pname = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<String> cl = (List<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new PredicateInst(pname,cl); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicate",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // predicate ::= MINUS ID LPAREN mixlist RPAREN 
            {
              PredicateInst RESULT =null;
		int pnameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int pnameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String pname = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int clleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int clright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<String> cl = (List<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new PredicateInst(pname,cl,true); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicate",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // predicate ::= ID LPAREN RPAREN 
            {
              PredicateInst RESULT =null;
		int pnameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pnameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String pname = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new PredicateInst(pname,false); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicate",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // predicate ::= MINUS ID LPAREN RPAREN 
            {
              PredicateInst RESULT =null;
		int pnameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pnameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String pname = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new PredicateInst(pname,true); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("predicate",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // mixlist ::= mixlist COMMA ID 
            {
              List<String> RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<String> m = (List<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		RESULT = m ; m.add(c);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mixlist",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // mixlist ::= ID 
            {
              List<String> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LinkedList<>(); RESULT.add(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mixlist",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // actiondecl ::= ACTIONS COL actionlist SEMI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actiondecl",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // actiondecl ::= ACTIONS actionlist SEMI 
            {
              Object RESULT =null;
		 warningMissing(":"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actiondecl",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // actionlist ::= actionlist actiond 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actionlist",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // actionlist ::= actiond 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actionlist",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // actiond ::= ID LPAREN mixlist RPAREN LCURLY precond postcond RCURLY 
            {
              Object RESULT =null;
		int actionNameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int actionNameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String actionName = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int varListleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int varListright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		List<String> varList = (List<String>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int preleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int preright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<PredicateInst> pre = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int postleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int postright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<PredicateInst> post = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 i.registerAction(actionName,varList,pre,post); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actiond",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // actiond ::= ID LPAREN RPAREN LCURLY precond postcond RCURLY 
            {
              Object RESULT =null;
		int actionNameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int actionNameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String actionName = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int preleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int preright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<PredicateInst> pre = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int postleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int postright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<PredicateInst> post = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 i.registerAction(actionName,null,pre,post); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actiond",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // precond ::= PRE COL predicates SEMI 
            {
              List<PredicateInst> RESULT =null;
		int ppleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ppright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<PredicateInst> pp = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = pp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("precond",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // precond ::= PRE COL SEMI 
            {
              List<PredicateInst> RESULT =null;
		RESULT = new LinkedList<PredicateInst>();
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("precond",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // postcond ::= POST COL predicates SEMI 
            {
              List<PredicateInst> RESULT =null;
		int ppleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ppright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<PredicateInst> pp = (List<PredicateInst>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = pp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("postcond",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // fileBreak ::= MANEOF 
            {
              Object RESULT =null;
		
//System.out.println("reached end of file");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fileBreak",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // PDDL ::= script runscripts predicatesdecl actiondecl fileBreak script constantsdecl initialdecl finaldecl script runscripts 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PDDL",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
