
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package lighthouse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACTIONS = 4;
  public static final int POST = 6;
  public static final int RPAREN = 8;
  public static final int INITIAL = 9;
  public static final int CONSTANTS = 11;
  public static final int SEMI = 2;
  public static final int SLASH = 13;
  public static final int PREDICATES = 10;
  public static final int RCURLY = 16;
  public static final int COL = 3;
  public static final int LPAREN = 7;
  public static final int ID = 20;
  public static final int LCURLY = 15;
  public static final int COMMA = 14;
  public static final int NUMBER = 21;
  public static final int MANEOF = 19;
  public static final int EOF = 0;
  public static final int SCRIPTBOUND = 18;
  public static final int MINUS = 17;
  public static final int PRE = 5;
  public static final int FINAL = 12;
  public static final int error = 1;
  public static final int SCRIPTCODE = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "COL",
  "ACTIONS",
  "PRE",
  "POST",
  "LPAREN",
  "RPAREN",
  "INITIAL",
  "PREDICATES",
  "CONSTANTS",
  "FINAL",
  "SLASH",
  "COMMA",
  "LCURLY",
  "RCURLY",
  "MINUS",
  "SCRIPTBOUND",
  "MANEOF",
  "ID",
  "NUMBER",
  "SCRIPTCODE"
  };
}

